config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  root to: 'offers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :offers do # only: %i[index show new create edit delete]
    resources :rents, only: [:create]
  end

  resources :reviews, only: [:destroy]
  resources :rents, only: [:destroy]

  # resources :rents, only: [:index, :show] do
  #   resources :reviews, only: [:new, :create]
  # end

  get "my_offers", to: "offers#my_offers"
  get "my_rents", to: "rents#my_rents"
  get "my_rents/:id/reviews", to: "reviews#new", as: :new_rent_reviews
  post "my_rents/:id/reviews", to: "reviews#create", as: :rent_reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :rents, dependent: :destroy
  has_many :reviews, through: :rents, dependent: :destroy

  has_one_attached :photo

  def rating
    unless self.reviews.nil?
      total = self.reviews.inject(0) { |sum, review| sum + review[:rating] }
      avg = total.fdiv(reviews.count).round(2)
      avg.nan? ? 'none' : avg
    end
  end

  def reviews
    rents = self.rents
    reviews = []
    rents.each do |rent|
      reviews << rent.review unless rent.review.nil?
    end
    return reviews
  end

end

# <%= link_to 'Avalie', new_offer_review_path(@offer) %>
# <div class="mx-2">
#             <%= link_to 'Apagar', review_path(review), method: :delete, data: { confirm: 'Tem certeza de que deseja apagar a avaliação?' } %>
#           </div>

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_one :review, dependent: :destroy

  # validate :date_cannot_be_in_the_past
  validate :final_date_greater_or_equal_to_begin_date
  validates :begin_date, presence: true
  validates :final_date, presence: true

  private

  def date_cannot_be_in_the_past
    errors.add(:begin_date, "can't be in the past") if begin_date.present? && begin_date < Date.today
    errors.add(:final_date, "can't be in the past") if final_date.present? && final_date < Date.today
  end

  def final_date_greater_or_equal_to_begin_date
    if final_date.present? && final_date < begin_date
      errors.add(:final_date, "final date must be greater or equal to begin date")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :rent

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :rent_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    include Pundit
  
    # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  
    # Uncomment when you *really understand* Pundit!
    # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # def user_not_authorized
    #   flash[:alert] = "You are not authorized to perform this action."
    #   redirect_to(root_path)
    # end
  
    private
  
    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
  end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: %i[index show]

  before_action :set_offer, only: %i[show edit update destroy]

  # GET /offers
  def index
    @offers = policy_scope(Offer) # .order(asc) se quiser colocar em ordem alfabética ou .order(created_at: :desc) para colocar os mais novos primeiros
  end

  # GET /offers/1
  def show
    @offer = Offer.find(params[:id])
    @rent = Rent.new
  end

  def my_offers
    @offers = Offer.where("user_id = ?", current_user.id)
    authorize @offers
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    authorize @offer
  end

  # GET /offers/1/edit
  def edit; end

  # POST /offers
  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer

    if @offer.save
      redirect_to offer_path(@offer), notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /offers/1
  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /offers/1
  def destroy
    @offer.destroy
    redirect_to offers_url, notice: 'Offer was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  # Only allow a trusted parameter "white list" through.
  def offer_params
    params.require(:offer).permit(:id, :name, :description, :offer_type, :size, :gender, :style, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :authenticate_user!

  # POST /rents
  def create
    @offer = Offer.find(params[:offer_id])
    @rent = Rent.new(rent_params)
    @rent.user = current_user
    @rent.offer = @offer
    @rent.price = @offer.price_per_day * (@rent.final_date - @rent.begin_date + 1)


    authorize @rent

    datas_ocupadas = period_avaliable
    if datas_ocupadas.zero?
      if @rent.save
        redirect_to offer_path(@offer), notice: 'Rent was successfully created.'
      else
        redirect_to offer_path(@offer), notice: 'At least one invalid date'
      end
    else
      msg = datas_ocupadas == 1 ? "One date is not available" : "#{datas_ocupadas} dates are not available"
      redirect_to offer_path(@offer), notice: msg
    end
  end

  # DELETE /rents/1
  def destroy
    @rent = Rent.find(params[:id])
    @rent.destroy
    redirect_to offer_path(@rent.offer), notice: 'Rent was successfully destroyed.'
    authorize @rent
  end

  def my_rents
    @rents = Rent.where("user_id = ?", current_user.id)
    authorize @rents
  end

  def show
    @rent = Rent.find(params[:id])
  end

  private

  # Only allow a trusted parameter "white list" through.
  def rent_params
    params.require(:rent).permit(:begin_date, :final_date)
  end

  def period_avaliable
    rents_offer = Rent.where(offer_id: @offer.id)
    bdate = @rent[:begin_date]
    edate = @rent[:final_date]
    datasocupadas = 0

    rents_offer.each do |rent|
      next unless rent.final_date >= Date.today

      (bdate..edate).each do |data|
        datasocupadas += 1 if (data >= rent.begin_date) && (data <= rent.final_date)
      end
    end
    return datasocupadas
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_rent, only: %i[new create]

  def new
    @review = Review.new
    @review.rent = @rent

    authorize @review
  end

  def create
    @review = Review.new(review_params)
    # we need `rent_id` to associate review with corresponding rent
    @review.rent = @rent

    authorize @review

    if @review.save
      redirect_to my_rents_path(anchor: "rent-#{@review.rent.id}"), notice: 'Avaliação criada com sucesso.'
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])

    authorize @review

    @review.destroy

    redirect_to offer_path(@review.rent.offer), notice: 'Avaliação apagada com sucesso.'
  end

  private

    def set_rent
      @rent = Rent.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppRoupa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_form.html.erb
<div>
  <%= simple_form_for(@offer) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
    
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :gender %>
      <%= f.input :style %>
      <%= f.input :size %>
      <%= f.input :price_per_day %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.submit 'Compartilhe', class: "btn btn-outline-secondary" %>
    </div>
  <% end %>
</div>

app/views/offers/edit.html.erb
<div class="container">
  <h1>Editing Offer</h1>

  <%= render 'form', offer: @offer %>

  <div class="my-4">
    <%= link_to 'Voltar', @offer, class: "btn btn-outline-secondary" %> |
    <%= link_to 'Ofertas', offers_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/offers/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("roupas.jpg") %>);">
  <div class="container">
    <h1>Me <strong>empresta</strong> hoje!</h1>
    <p>Que roupa você quer usar?</p>
  </div>
</div>

<div class="container">

  <div class="cards">
    <% @offers.each do |offer| %>
      <div class="card-trip">
        <% if offer.photo.attached? %>
          <%= cl_image_tag offer.photo.key, height: 200, width: 200, crop: :fill %>
        <% else %>
          <p><%= image_tag "vestido_no_cabide.jpg", height: 200, width: 200, crop: :fill %></p>
        <% end %>
        <div class="card-trip-infos">

          <div>
            <h2><%= link_to offer.name.capitalize, offer_path(offer), class: "a-primary" %></h2>
            <p><%= offer.description %></p>
          </div>
          <div class="card-trip-pricing">
            <% if offer.user == current_user %>
              <p><%= link_to 'Editar', edit_offer_path(offer), class: "a-primary"%></p>
              <p><%= link_to 'Apagar', offer, method: :delete, data: { confirm: 'Are you sure?' }, class: "a-primary"%></p>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/offers/my_offers.html.erb
<div class="container">
  <h1>Minhas roupas</h1>
  <div class="cards">
    <% @offers.each do |offer| %>
      <div class="card-trip">
        <% if offer.photo.attached? %>
          <%= cl_image_tag offer.photo.key, height: 200, width: 200, crop: :fill %>
        <% else %>
          <p><%= image_tag("cabide.jpg") %></p>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to offer.name.capitalize, offer_path(offer), class: "a-primary" %></h2>
            <p><%= offer.description %></p>
          </div>
          <div class="card-trip-pricing">
            <p><%= link_to 'Editar', edit_offer_path(offer), class: "a-primary"%></p>
            <p><%= link_to 'Apagar', offer, method: :delete, data: { confirm: 'Are you sure?' }, class: "a-primary"%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container">
  <div class="form">
    <br>
    <h1>O que você vai emprestar?</h1>

    <%= render 'form', offer: @offer%>
    <div class="my-4">
      <%= link_to 'Voltar', offers_path, class: "a-primary"%>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <h2><strong>Me empresta hoje!</strong></h2>
  <br>
  <div style="width: 100%; display: table;">

    <div style="display: table-row;">
      <div style="width: 50%; display: table-cell;">
        <h3><strong>Oferta</strong></h3>
        <h4><%= @offer.name %></h6>
        <div>
          <% if @offer.photo.present? %>
            <%= cl_image_tag @offer.photo.key, height: 400, width: 400, crop: :fill %>

          <% else %>
            <%= image_tag "vestido_no_cabide.jpg", height: 400, width: 400, crop: :fill %>
          <% end %>
        </div>
        <div class="my-3">
          <h5><%= @offer.description %></h5>
        </div>
        <div class="d-flex my-3">
          <div class="m-2">
            <strong>Gênero:</strong>
            <%= @offer.gender %>
          </div>
          <div class="m-2">
            <strong>Estilo:</strong>
            <%= @offer.style %>
          </div>
          <div class="m-2">
            <strong>Tamanho:</strong>
            <%= @offer.size %>
          </div>
        </div>
        <div>
            <h4>Diária: <strong> R$ <%= '%.2f' % @offer.price_per_day %></strong></h4>
        </div>
      <div>
      <div>

      </div>
        <div class="my-4">
          <% if policy(@offer).edit? %>
            <%= link_to 'Editar', edit_offer_path(@offer), class: "btn btn-outline-secondary" %>
          <% end %>
          <% if policy(@offer).destroy? %>
            <%= link_to 'Apagar', offer_path, method: :delete, class: "btn btn-outline-secondary", data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
        <div class="my-4">
          <%= link_to 'Voltar', offers_path, class:"btn btn-outline-secondary" %>
        </div>
      </div>
      <br>
    </div>
    <div style="display: table-cell;">
      <h3><strong>Aluguéis</strong></h3>
      <div>
        <table class="table table-bordered">
          <tbody>
            <thead>
              <th>Seq</th>
              <th>Data Início</th>
              <th>Data Fim</th>
              <th>Valor</th>
              <% if @offer.user == current_user %>
                <th>Excluir</th>
              <% end %>

            </thead>
            <% i = 0 %>
            <% offer_ordered = @offer.rents.order("begin_date").all %>
            <% offer_ordered.each do |rent| %>
              <% if @offer.user == current_user || rent.final_date >= Date.today %>
                <tr>
                  <% i = i + 1 %>
                  <td><%= i %></td>
                  <td><%= rent.begin_date %></td>
                  <td><%= rent.final_date %></td>
                  <% if @offer.user == current_user || rent.user == current_user %>
                    <td><%= rent.price %></td>
                  <% else %>
                    <td>-x-</td>

                  <% end %>
                  <% if @offer.user == current_user && rent.final_date < Date.today%>
                    <td>
                      <%= link_to rent_path(rent), method: :delete, data: { confirm: "Are you sure?" } do %>
                        <i class="fa fa-trash"></i>
                      <% end %>
                    </td>
                  <% end %>
                  <% if @offer.user == current_user %>
                    <td></td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
            <% if i == 0 %>
              <tr>
                <% if @offer.user == current_user %>
                  <td>Esta oferta nunca foi alugada</td>
                <% else %>
                  <td>Nenhum aluguel reservado</td>
                <% end %>
                <td></td>
                <td></td>
                <td></td>
                <% if @offer.user == current_user %>
                  <td></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <br>
      <% if not @offer.user == current_user %>
        <div>
          <%= render "rents/new", offer: @offer, rent: @rent %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="my-5">
    <h2>Avaliações</h2>
    <ul class="list-group">
      <% @offer.reviews.each do |review| %>
        <li class="list-group-item d-flex">
          <div class="mx-2">
            <%= review.content %>
          </div>
          <div class="mx-2">
            <strong>Nota: <%= review.rating %>/5</strong>
          </div>
          <div class="mx-2">
            <% if policy(review).destroy? %>
              <%= link_to review_path(review), method: :delete, data: { confirm: "Tem certeza que deseja apagar a avaliação?" } do %>
                <i class="fa fa-trash destroy_dose btn-outline-secondary"></i>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>

  </div>
</div>


<!-- ... -->

app/views/pages/home.html.erb
<h1>Me empresta hoje</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rents/_new.html.erb
<h3><strong>Escolha o período:<strong></h3>
<%= simple_form_for [offer, rent] do |f| %>
  <%= f.input :begin_date, label: 'Data Início' %>
  <%= f.input :final_date, label: 'Data Final' %>
  <%= f.button :submit, "Alugar", class: "btn btn-outline-secondary" %>
<% end %>

app/views/rents/my_rents.html.erb
<div class="container">
  <h1>Roupas alugadas</h1>
  <div class="cards">
    <% @rents.each do |rent| %>
      <div class="card-trip" id="<%="rent-#{rent.id}"%>">
        <% if rent.offer.photo.attached? %>
          <%= cl_image_tag rent.offer.photo.key, height: 200, width: 200, crop: :fill %>
        <% else %>
          <p><%= image_tag("cabide.jpg") %></p>
        <% end %>
        <div class="text-center my-2">
          <%= link_to "Avaliar", new_rent_reviews_path(rent), class: "btn btn-outline-secondary
            #{' disabled' unless (rent.review.nil? && rent.final_date < Date.today) }" %>
        </div>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to rent.offer.name.capitalize, offer_path(rent.offer), class: "a-primary" %></h2>
            <p>Valor: <%= rent.price %></p>
          </div>
          <div class="card-trip-pricing">
            <p> Alugado em: <%= rent.begin_date %></p>
            <p> até: <%= rent.final_date %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [ @rent, @review ] do |f| %>
    <%= f.input :content, class: "form-control" %>
    <%= f.input :rating, class: "form-control" %>
    <%= f.submit "Enviar avaliação", class: "btn btn-outline-secondary" %>
  <% end %>

  <div class="my-4">
    <%= link_to 'Voltar', my_rents_path, class: "btn-outline-secondary" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
    <%= link_to offers_path, class: "navbar-brand" do %>
      <%= image_tag "https://image.flaticon.com/icons/png/512/80/80875.png" %>
      <% end %>
    <% if policy(Offer).create? %>
        <a class="btn btn-ghost" <%= link_to 'Empreste aqui', new_offer_path %> </a>
      <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <span class="nav-link">
            <%= current_user.email %>
          </span>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://www.clipartmax.com/png/middle/112-1124080_monica-hernandez-facebook-avatar-woman.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Atualizar cadastro", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Minhas roupas", my_offers_path, class: "dropdown-item" %>
            <%= link_to "Roupas alugadas", my_rents_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>